# Generated by Django 4.2.2 on 2023-06-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('dni_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_cliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'clientes de estacionamiento',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('idparcela', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_parcela', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'parcela estacionamiento',
                'verbose_name_plural': 'parcelas',
                'db_table': 'parcela',
            },
        ),
        migrations.CreateModel(
            name='sector_estacionamiento',
            fields=[
                ('idsector', models.AutoField(primary_key=True, serialize=False)),
                ('descrpcion_sector', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'sector estacionamiento',
                'verbose_name_plural': 'sectores de estacionamiento',
                'db_table': 'sector_estacionamiento',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('idvehiculos', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.clientes')),
                ('idparcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.parcela')),
            ],
            options={
                'verbose_name': 'vehiculos estacionados',
                'verbose_name_plural': 'vehiculos',
                'db_table': 'vehiculos',
            },
        ),
        migrations.AddField(
            model_name='parcela',
            name='idsector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.sector_estacionamiento'),
        ),
    ]
