# Generated by Django 4.2.1 on 2023-05-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('dni_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_cliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'clientes de estacionamiento',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('patente', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.clientes')),
            ],
            options={
                'verbose_name': 'vehicuñlos estacionados',
                'verbose_name_plural': 'vehiculos',
                'db_table': 'vehiculos',
            },
        ),
    ]
